"""empty message

Revision ID: b7031138dc9f
Revises: 
Create Date: 2018-12-15 11:59:54.303435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7031138dc9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procpect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('prenom', sa.String(), nullable=True),
    sa.Column('tel', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('wilaya', sa.String(), nullable=True),
    sa.Column('ville', sa.String(), nullable=True),
    sa.Column('visite_realisee', sa.String(), nullable=True),
    sa.Column('achat_effectuee_chez_le_promoteur', sa.String(), nullable=True),
    sa.Column('achat_efectue_ailleurs', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('remarque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('remarque_procpect',
    sa.Column('procpect_id', sa.Integer(), nullable=False),
    sa.Column('remarque_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['procpect_id'], ['procpect.id'], ),
    sa.ForeignKeyConstraint(['remarque_id'], ['remarque.id'], ),
    sa.PrimaryKeyConstraint('procpect_id', 'remarque_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('remarque_procpect')
    op.drop_table('user')
    op.drop_table('remarque')
    op.drop_table('project')
    op.drop_table('procpect')
    # ### end Alembic commands ###
